# To generate random numbers, the code below is used
import random
# this code is to aid in generating random integers between 1 and 99
value=random.randint(1,99)
# the while loop is to help execute the lines of codes that come underneath
while value:

    value = random.randint(1, 99)
# this code is telling the user to guess an integer that falls between 1 and 99
    user_input=int(input("Guess a number: "))
#  random number given by the user is greater than the number generated by the program, then the output should be wrong
    if user_input > value:
        print('wrong your guess is too high')
# random number given by the user is less than the number generated by the program, then the output should be wrong
    elif user_input < value:
        print("wrong your guess is too low")
# when user's input is the same as the number generated by the program then the answer is correct
    else:
        print("correct your answer is correct")
# after the user has gotten the answer correct,the break statement terminates the loop
        break
